# Generated by Django 6.0.2 on 2026-02-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
