# Generated by Django 6.0.2 on 2026-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationslpitemtypes',
            name='material_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporationslpitemtypes',
            name='required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
