# Generated by Django 6.0.2 on 2026-02-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_categories_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
