# Generated by Django 6.0.2 on 2026-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_corporationslpitemtypes_material_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationslpitemtypes',
            name='required',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
