# Generated by Django 6.0.2 on 2026-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_marketgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketgroups',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='marketgroups',
            name='published',
        ),
        migrations.AddField(
            model_name='marketgroups',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
