# Generated by Django 6.0.2 on 2026-02-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_remove_marketgroups_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='industry.categories'),
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('packaged_volume', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('portion_size', models.IntegerField(blank=True, null=True)),
                ('graphic_id', models.IntegerField(blank=True, null=True)),
                ('icon_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.groups')),
                ('market_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.marketgroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
