# Generated by Django 6.0.2 on 2026-02-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_alter_types_market_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.groups'),
        ),
    ]
