# Generated by Django 6.0.2 on 2026-02-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_alter_types_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrices',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_id', models.OneToOneField(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='market_prices', serialize=False, to='industry.types')),
                ('adjusted_price', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='types',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.groups'),
        ),
        migrations.AlterField(
            model_name='types',
            name='market_group_id',
            field=models.ForeignKey(blank=True, db_column='market_group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.marketgroups'),
        ),
    ]
