# Generated by Django 6.0.2 on 2026-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_marketprices_alter_types_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationsWithLPStores',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('corporation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('home_station_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20)),
                ('war_eligible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
