# Generated by Django 6.0.2 on 2026-02-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0010_corporationswithlpstores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationsLpItemTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('ak_cost', models.IntegerField(blank=True, null=True)),
                ('isk_cost', models.IntegerField(blank=True, null=True)),
                ('lp_cost', models.IntegerField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('required_items', models.JSONField(blank=True, null=True)),
                ('corporation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_store_offers', to='industry.corporationswithlpstores')),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, related_name='lp_store_offers', to='industry.types')),
            ],
            options={
                'unique_together': {('type_id', 'corporation_id')},
            },
        ),
        migrations.AddField(
            model_name='corporationswithlpstores',
            name='type_id',
            field=models.ManyToManyField(through='industry.CorporationsLpItemTypes', to='industry.types'),
        ),
    ]
