# Generated by Django 6.0.2 on 2026-02-19 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0011_corporationslpitemtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationslpitemtypes',
            name='corporation_id',
            field=models.ForeignKey(db_column='corporation_id', on_delete=django.db.models.deletion.CASCADE, related_name='lp_store_offers', to='industry.corporationswithlpstores'),
        ),
    ]
